OBJS := gpio-api.o
#CFLAGS := -fpic
CC := /opt/gcc-linaro-5.4.1-2017.05-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc
#TARGET := libgpio.so

all: $(OBJS)
#	$(CC) -shared $(OBJS) -o $(TARGET)

.PHONY: clean

clean:
	rm -rf *.o *.so